services:
  - type: web
    name: first-django-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py collectstatic --noinput && python manage.py migrate && gunicorn todo_list.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.4"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
